# _config.yml
title: George P. Mathew | Materials Engineer
description: >-
  Aspiring Materials Engineer with a foundation in Civil Engineering.
  Currently pursuing a Master's at RWTH Aachen.
theme: jekyll-theme-minimal
